### ISSUE TITLE
npm copy script has typo in package.json

### ISSUE THREAD

**Issue by mindcat** [gittyeric/ergodox-macro-hax#13]
line 10: "copy": "cpy ./layouty_src/..."
SHOULD BE ->
 line 10: "copy": "cpy ./layout_src/..."

**Comment by Phoscur** [comment]
Oh you got me there, I guess I did not need it anymore later...

**Comment by Phoscur** [comment]
Fixed by @sytone: https://github.com/Phoscur/oryx-macro-hax/blob/main/package.json#L12

The project is being migrated to my fork.
