### ISSUE TITLE
Addition of macros in the dance actions

### ISSUE THREAD

**Issue by sytone** [gittyeric/ergodox-macro-hax#14]
Made a fork and allowed the SINGLE_TAP, SINGLE_HOLD, DOUBLE_TAP and DOUBLE_HOLD steps in the dance function be replaced with macros without having to have a fully manual keymap. You can modify via onyx and use this to get the latest and patch. 

Also moved to use .env file and environment variables to remove hard coding.

Leaving a message here in case anyone wants to use this.

**Comment by sytone** [comment]
Fork: https://github.com/sytone/ergodox-macro-hax

I am using this with my moonlander.

**Comment by Phoscur** [comment]
Hi @sytone,
Welcome to our little moonlander macro hax community!
I haven't tried tap dances yet, but after looking through your fork I think I really should :)

I'm switching to MacOS again for work, so I'll need to add some hax to switch keys around (Cmd<->Ctrl), I'm pretty sure that will make me work on my fork around or after easter.

Have you tried to build your firmware in Github Actions? That was my major contribution to this repo, and I am looking to keep maintaining it!
Please leave a comment in this thread https://github.com/gittyeric/ergodox-macro-hax/issues/7, I would like to know what you think or if you have a different approach.

**Comment by sytone** [comment]
I have not had a chance to look at github, I am using WSL to build locally at the moment.

**Comment by Phoscur** [comment]
> I have not had a chance to look at github, I am using WSL to build locally at the moment.

Why WSL, not native Windows?

Btw:
I've noticed the `cross-var` package being unmaintained, why exactly do we need it?

**Comment by Phoscur** [comment]
I've merged your commits in merged in https://github.com/Phoscur/oryx-macro-hax/pull/1
please add https://github.com/Phoscur/oryx-macro-hax as upstream, rebase and add check if everything still works for you!

I'm adding something towards the original idea of #7, so we can stop commenting out each others macros - in the upcoming days.

**Comment by Phoscur** [comment]
Saw your comment about refactoring the processAll function, and did that! I hope you will like my improvements and you can test them?
https://github.com/Phoscur/oryx-macro-hax/pull/3

**Comment by Phoscur** [comment]
Merged and started the migration to my fork, please confirm if it still works after my recent changes so we can close here @sytone 

Needed to remove `cross-env` to get a clean `npm audit`.

**Comment by gittyeric** [comment]
Closing in favor of of Phosphor's now-canonical [fork](https://github.com/Phoscur/oryx-macro-hax)!
