### ISSUE TITLE
Application Quick Launches

### ISSUE THREAD

**Issue by Phoscur** [gittyeric/ergodox-macro-hax#2]
The lauch application macros are commented out, why?

Maybe it would be better to use `Win+R` instead of going through the search?

**Comment by eric-fulfil** [comment]
I don't quite remember, I probably left it for reference.  App launch macros are highly OS-dependent so I think this was trying to do Mac Spotlight search.

**Comment by BluestDragon** [comment]
Interesting! It also works on windows (just not always and a bit clunky), so it is actually OS-independent like that...
Thank you for the answer!

**Comment by Phoscur** [comment]
Interesting! It also works on windows (just not always and a bit clunky), so it is actually OS-independent like that...
Thank you for the answer!

**Comment by gittyeric** [comment]
Closing in favor of of Phosphor's now-canonical [fork](https://github.com/Phoscur/oryx-macro-hax)!
