### ISSUE TITLE
Add instructions to switch git upstream and forward collaborators to Phoscur's fork

### ISSUE THREAD

**Issue by Phoscur** [gittyeric/ergodox-macro-hax#9]
Split from [#7 see infos in comment why this needs to be approached slowly](https://github.com/gittyeric/ergodox-macro-hax/issues/7#issuecomment-1158737631)
# Keep collaborator motivation while slowly migrating
>> push the idea again of your fork becoming the canonical one and I can update the README here to link to yours whenever you're ready for it

> What's the default process for this? Does every fork need to adopt the new upstream then, or can it be forwarded somehow? I guess you are adding `git add remote upstream` and `git branch --set-upstream-to` instructions to the README?

@gittyeric I think we can/should already start adding infos about this upcoming migration, but please give it lots of time until we close here!

**Comment by Phoscur** [comment]
> https://stackoverflow.com/questions/16052477/delete-fork-dependency-of-a-github-repository

^ This one is interesting concerning making a fork the main repo!

@gittyeric would you please elaborate on how exactly you planned to migrate? I see there is #12 prepared to add a first doc paragraph…

Since we still haven't made much progress here, I also see the opportunity for @5andr0 to pick up the burden of leading this hax community with his fork!

**Comment by gittyeric** [comment]
Yeah I'm thinking there's little more to be done than update the readme to point to the canoncial fork. In terms of "looking" like the original, it could be as simple as committing a fresh repo containing everything in here, or getting lucky with GH support like in your link there.  If @5andr0 would like to, I can point this README over to his fork.  I don't think there's much more to do than that for the migration.  The only canonical fork switching I've seen is pretty much that, just state on the first line that the new fork URL is now the maintained one.

If @5andr0 or anyone else promises to carry forward teh hax with love them I'll all for it.  I'd happily continue to merge PRs myself except for lacking the hardware to test properly.

**Comment by Phoscur** [comment]
I'll take it on, I've also created the QMK-Compile, which I am continuing to maintain. 
Looking at current PR's, I think you only want to merge this one https://github.com/gittyeric/ergodox-macro-hax/pull/12

**Comment by Phoscur** [comment]
Merged #12 - now what remains is adding more detailed info how to migrate after asking support to help us? @gittyeric I think you need to ask Github Support, as you are still the repo owner.

In the end, it should no longer say "forked from https://github.com/gittyeric/ergodox-macro-hax" under my repo name
[oryx-macro-hax](https://github.com/Phoscur/oryx-macro-hax)

**Comment by gittyeric** [comment]
@Phoscur let me look into this, I'll leave this last Issue open on this repo to track as I've never done this.

**Comment by gittyeric** [comment]
Submitted the following:

`I started the repo https://github.com/gittyeric/ergodox-macro-hax which has been taken over by the https://github.com/Phoscur/oryx-macro-hax fork.  I'd like to make Phoscur's fork the canonical one with originating credit.`

:crossed_fingers:

**Comment by Phoscur** [comment]
Oh wow they already did it? It now says your fork derives from mine :)
Very nice, thank you for the great collaboration!
